insert into abonent values(null, 'Aidyn','Jussupov','male','Seifullin Str.');
insert into abonent values(null, 'Alisher','Zhanbulat','male','Abylaikhan Str.');
insert into abonent values(null, 'Madina','Zhamaliyeva','female','Altynaul Str.');
insert into abonent values(null, 'Yevgeniy','Cherlenok','male','Altynaul Str.');
insert into abonent values(null, 'Aidana','Lesbek','female','Altynaul Str.');
insert into abonent values(null, 'Dinmukhammed','Siyezkan','male','Altynaul Str.');
insert into abonent values(null, 'Aisaule','Bazarkulova','female','Altynaul Str.');
insert into abonent values(null, 'Zhangir','Berdenov','male','Altynaul Str.');
insert into abonent values(null, 'Madina','Tazhiyeva','female','Seifullin Str.');
insert into abonent values(null, 'Aliya','Moldagulova','female','Nazarbayev Str.');
insert into abonent values(null, 'Aigul','Ryspayeva','female','Istaya Str.');
insert into abonent values(null, 'Ilyas','Kurmanbayev','male','Saina Str.');
insert into abonent values(null, 'Azamat','Khan','male','Al Farabi Str.');
insert into abonent values(null, 'Saule','Kozhakhmet','female','Jambul Str.');
insert into abonent values(null, 'Dinara','Khan','female','Manasa Str.');
insert into abonent values(null, 'Dinmukhammed','Ondassyn','male','Baitursynov Str.');

insert into operator values(null, 'Altel');
insert into operator values(null, 'MTC');
insert into operator values(null, 'Megafon');
insert into operator values(null, 'Vivacom');
insert into operator values(null, 'MTel');
insert into operator values(null, 'Neo');
insert into operator values(null, 'Star');
insert into operator values(null, 'Kcell');
insert into operator values(null, 'Turkcell');
insert into operator values(null, 'Tele2');
insert into operator values(null, 'Beeline');
insert into operator values(null, 'Bulsatkom');
insert into operator values(null, 'Delux');

insert into tarif values(null, 1, 'No Limits', 233);
insert into tarif values(null, 1, 'Internet Free',434 );
insert into tarif values(null, 2, 'Call',543 );
insert into tarif values(null, 1, 'All Included',123 );
insert into tarif values(null, 3, 'Smart call',444 );
insert into tarif values(null, 4, '3G', 654);
insert into tarif values(null, 2, '500 calls', 324);
insert into tarif values(null, 4, 'Free Calls',234 );
insert into tarif values(null, 5, 'Message free', 445);
insert into tarif values(null, 11, 'Red 4G', 545);
insert into tarif values(null, 5, 'LTE free', 456);
insert into tarif values(null, 5, 'Corporative', 345);
insert into tarif values(null, 6, 'Office',483 );
insert into tarif values(null, 7, 'Grand Operator', 239);
insert into tarif values(null, 7, 'Best Times',138 );
insert into tarif values(null, 6, 'Everything', 134);
insert into tarif values(null, 8, 'Family Time', 353);
insert into tarif values(null, 9, 'Summer Ring', 234);
insert into tarif values(null, 10, 'Double Internet',543 );
insert into tarif values(null, 10, 'Social Media free', 654);
insert into tarif values(null, 11, 'Access', 364);
insert into tarif values(null, 13, 'My Home', 375);
insert into tarif values(null, 10, 'For Modem', 546);
insert into tarif values(null, 5, 'Available 24/7', 464);
insert into tarif values(null, 11, 'No restrictions', 273 );
insert into tarif values(null, 4, 'Simple', 243);
insert into tarif values(null, 3, 'Sms and calls', 746);
insert into tarif values(null, 2, 'For children', 324);
insert into tarif values(null, 5, 'University',765 );

insert into connection values(null, null, 1);
insert into connection values(null, null, 2);
insert into connection values(null, null, 3);
insert into connection values(null, null, 4);
insert into connection values(null, null, 5);
insert into connection values(null, null, 6);
insert into connection values(null, null, 7);
insert into connection values(null, null, 8);
insert into connection values(null, null, 9);
insert into connection values(null, null, 10);
insert into connection values(null, null, 11);
insert into connection values(null, null, 10);
insert into connection values(null, null, 9);
insert into connection values(null, null, 8);
insert into connection values(null, null, 7);
insert into connection values(null, null, 6);
insert into connection values(null, null, 5);
insert into connection values(null, null, 4);


insert into dolg values(null, null, 1200);
insert into dolg values(null, null, 0);
insert into dolg values(null, null, 1350);
insert into dolg values(null, null, 500);
insert into dolg values(null, null, 2700);
insert into dolg values(null, null, 0);
insert into dolg values(null, null, 0);
insert into dolg values(null, null, 0);
insert into dolg values(null, null, 1500);
insert into dolg values(null, null, 5600);
insert into dolg values(null, null, 3500);
insert into dolg values(null, null, 2300);
insert into dolg values(null, null, 2300);
insert into dolg values(null, null, 1200);
insert into dolg values(null, null, 1000);
insert into dolg values(null, null, 500);
insert into dolg values(null, null, 4000);

insert into address values(null, null, 'Saina', 12);
insert into address values(null, null, 'Tolebi', 55);
insert into address values(null, null, 'Altynaul',34 );
insert into address values(null, null, 'Zhanuya', 23);
insert into address values(null, null, 'Raiymbek', 23);
insert into address values(null, null, 'Kabanbay Batyr', 11);
insert into address values(null, null, 'Salonnaya', 14);
insert into address values(null, null, 'Nazarbayeva', 65);
insert into address values(null, null, 'Baitursynova', 37);
insert into address values(null, null, 'Altynaul', 77);
insert into address values(null, null, 'Zhetysu', 34);
insert into address values(null, null, 'Shymbulak', 87);
insert into address values(null, null, 'Medeu', 92);
insert into address values(null, null, 'Kolonnaya', 12);
insert into address values(null, null, 'Pobeda',16 );
insert into address values(null, null, 'Dostyk', 14);

